name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  "build-and-test":
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build .

    - name: Test
      run: go test -v ./...

    - name: Check README up-to-date
      run: go run ./scripts/update_readme.go -mode check
